### ISSUE TITLE
Example without `with` statement?

### ISSUE THREAD

**Issue by mankoff** [zarch/grass-session#1]
This looks useful, thank you for developing it.

When I run GRASS in Python (without officially starting GRASS) I use the code example here: https://grasswiki.osgeo.org/wiki/Working_with_GRASS_without_starting_it_explicitly#Python:_GRASS_GIS_7_with_existing_location and then can write Python code that looks fairly similar to the bash code. For example, I initialize my environment with:
 
```
import os
import sys
import subprocess

location = "G" if 'location' not in locals() else location
mapset = "PERMANENT" if 'mapset' not in locals() else mapset

startcmd = ['grass72', '--config', 'path']
p = subprocess.Popen(startcmd, shell=False,stdout=subprocess.PIPE, stderr=subprocess.PIPE)
out, err = p.communicate()
gisbase = out.decode('utf-8').strip()
os.environ['GISBASE'] = gisbase
sys.path.append(os.path.join(gisbase, "etc", "python"))
gisdb = os.path.join(".")
os.environ['GISDBASE'] = gisdb
import grass.script as gs
import grass.script.setup as gsetup
rcfile = gsetup.init(gisbase, gisdb, location, mapset)
```

Import some modules:

```
from grass.pygrass.modules.shortcuts import general as g
from grass.pygrass.modules.shortcuts import raster as r
from grass.pygrass.modules.shortcuts import vector as v
from grass.pygrass.modules.shortcuts import display as d
from grass.script import array as garray
```

And then can use them:

```
g.mapsets(flags="l")
g.list(type="raster", flags="m")
```

Is it possible to use your library to simplify the first code block above, and then allow me to import the grass modules as per the 2nd code block, and use them as per the 3rd? I can see how to do this within your `with` block, but I'd like to be able to do it outside a `with` block. Is this possible? Can you provide an example if it is?

Thank you

**Comment by zarch** [comment]
> Is it possible to use your library to simplify the first code block above, and then allow me to import the grass modules as per the 2nd code block, and use them as per the 3rd? I can see how to do this within your with block, but I'd like to be able to do it outside a with block. Is this possible? Can you provide an example if it is?

yes, i've just fixed some small bugs, so now you can write:


```python
import os

# import grass_session
from grass_session import Session

# import grass python libraries
from grass.pygrass.modules.shortcuts import general as g


# set some common environmental variables, like:
os.environ.update(dict(GRASS_COMPRESS_NULLS='1',
                       GRASS_COMPRESSOR='ZSTD'))

# create a PERMANENT mapset
# create a Session instance
PERMANENT = Session()
PERMANENT.open(gisdb='/tmp', location='mytest',
               create_opts='EPSG:4326')


# execute some command inside PERMANENT
g.mapsets(flags="l")
g.list(type="raster", flags="m")

# exit from PERMANENT
PERMANENT.close()

# create a new mapset in the same location
user = Session()
user.open(gisdb='/tmp', location='mytest', mapset='user',
               create_opts='')

# execute some command inside user
g.mapsets(flags="l")
g.list(type="raster", flags="m")

# exit from user
user.close()
```

So the idea is to have a similar behaviour like to open a file, or open a connection to a database.

**Comment by zarch** [comment]
I've added the example in the wikipage, feel free to improve it.

**Comment by mankoff** [comment]
This is a nice feature addition. Thank you! I don't see a wiki page on GitHub.
