### ISSUE TITLE
Hardcoded locale variables

### ISSUE THREAD

**Issue by davebrent** [zarch/grass-session#10]
Hi, I've run into a small problem while using `grass-session`.

When running grass in the regular way, I am able to run `v.import`, with a simple file, in a different projection to my current grass location, and it will be reprojected into my mapset as expected.

But when doing the same from a python script, with the same file and location, that uses `grass-session`, I get warnings such as this:

```
WARNING: Unable to open datum table file <Default locale not found, using
         UTF-8
         /usr/lib64/grass74/etc/proj/datum.table>
WARNING: Datum <WGS_1984> not recognised by GRASS and no parameters found
WARNING: Unable to open ellipsoid table file <Default locale not found,
         using UTF-8
         /usr/lib64/grass74/etc/proj/ellipse.table>
```

And my import will eventually fail with:

```
Default driver / database set to:
driver: sqlite
database: $GISDBASE/$LOCATION_NAME/$MAPSET/sqlite/sqlite.db
No such file or directory: Cannot open drivers directory
WARNING: Unable to start driver <sqlite>
ERROR: Unable to open database
       </grassdata/temp_import_location_2131/PERMANENT/sqlite/sqlite.db>
       by driver <sqlite>
```

But, if I remove the hard coded locale variables in `grass-session`, everything works as expected:

```diff
diff --git a/grass_session/session.py b/grass_session/session.py
index 335660d..62f9d17 100644
--- a/grass_session/session.py
+++ b/grass_session/session.py
@@ -128,9 +128,6 @@ def set_grass_path_env(gisbase=None, env=None, grassbin=None):
     if grasspy not in sys.path:
         sys.path.insert(0, grasspy)

-    env['LANG'] = 'en_US.UTF-8'
-    env['LOCALE'] = 'C'
-    env['LC_ALL'] = 'C'
     return env
```

Im not sure of the original case for explicitly setting these variables (Windows?), but looking at [`set_language` in grass][1] my reading of it is, other than trying to load wxGUI preferences, is that nothing needs to be done if these variables are already set, and that the C locale is only used as a fallback.

  [1]: https://trac.osgeo.org/grass/browser/grass/trunk/lib/init/grass.py#L1234

My system settings:

```
Operating System: Fedora 29 (Server Edition)
Kernel: Linux 4.20.16-200.fc29.x86_64

GRASS GIS 7.4.4
python 2.7 & python 3.7

LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```

**Comment by zarch** [comment]
Dear @davebrent,
this is weird... 
I will test it on my computer. 
In a meanwhile, would you like to make PR with the change?

**Comment by zarch** [comment]
@davebrent I created a PR and it is now merged on the `develop` branch.

**Comment by davebrent** [comment]
Great thank you @zarch !
