### ISSUE TITLE
pip install grass-session

### ISSUE THREAD

**Issue by landam** [zarch/grass-session#2]
In Readme it's mentioned 

```
pip install grass-session
```

but it fails

```
pip install grass_session
Collecting grass_session
  Could not find a version that satisfies the requirement grass_session (from versions: )
No matching distribution found for grass_session
```

**Comment by zarch** [comment]
Today I published `grass-session` on pypi, you can find the package here:

https://pypi.python.org/pypi/grass-session/

The command:

```bash
pip install grass-session
```
it is now working on my computer, let me know if it works on yours as well.
If yes I'm going to close the issue.

**Comment by landam** [comment]
Great, works.
