### ISSUE TITLE
RuntimeError / Start script not found

### ISSUE THREAD

**Issue by maawoo** [zarch/grass-session#20]
Hi there!
I'm working on a small university project that implements GRASS using grass-session. It works without any problems on Windows10 and now I'm trying to get it to work on Linux. 
On Windows I had to add the base directory of my installation `C:\Program Files\GRASS GIS 7.8` to the PATH system variable so the start script `grass78.bat` could be found by grass-session. 
On Linux I added the following to my `.bashrc`:
```
export LD_LIBRARY_PATH=/usr/lib/grass78/lib
export GRASSBIN=/usr/bin/grass78
```
Based on information I found [here](https://grasswiki.osgeo.org/wiki/Working_with_GRASS_without_starting_it_explicitly). But grass-session still can't find the start script and gives me the following error during import:

```
>>>from grass_session import Session, get_grass_gisbase
cmd: grass78 --config path
out: b''
err: b'/bin/sh: grass78: command not found\n'
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/app/pycharm/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/marco/miniconda3/envs/S1GRASS_env/lib/python3.7/site-packages/grass_session/__init__.py", line 4, in <module>
    from grass_session.session import (
  File "/app/pycharm/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/marco/miniconda3/envs/S1GRASS_env/lib/python3.7/site-packages/grass_session/session.py", line 519, in <module>
    GISBASE = get_grass_gisbase(grassbin=GRASSBIN)
  File "/home/marco/miniconda3/envs/S1GRASS_env/lib/python3.7/site-packages/grass_session/session.py", line 142, in get_grass_gisbase
    ).format(grassbin=grassbin)
RuntimeError: Cannot find GRASS GIS start script: grass78, set the right one using the GRASSBIN environm. variable
``` 
Especially the first lines seem weird to me, because when I run `grass78 --config path` in the terminal, I get the path `/usr/lib/grass78` instead of an empty string. 

Is there something obvious I'm doing wrong? I'm confused as to what should and shouldn't be done, which variables should or need to be set in the python script and which ones beforehand in system variables...

**Comment by zarch** [comment]
Sorry @maawoo for the delay, have you already fix the issue?
Have you open a new shell after the change in the bashrc file?

Have you try executing the file with something like:

```bash
GRASSBIN="grass78" LD_LIBRARY_PATH="$($GRASSBIN --config path)/lib" python3 yourprogram.py
```

**Comment by maawoo** [comment]
Hi @zarch! 
No problem. I'm pretty sure that I've somehow managed to solve this issue back then. I initially opened it while working on a project for a Master's degree course and I successfully finished the course as well as my degree actually 😃
So I'll just close this. Sorry for not doing that earlier! 

Cheers, Marco
