### ISSUE TITLE
GRASS_ADDON_PATH not added to PATH

### ISSUE THREAD

**Issue by albertoparadisllop** [zarch/grass-session#23]
As the [official documentation](https://grass.osgeo.org/grass78/manuals/grass7.html) says, if `GRASS_ADDON_PATH` is defined, it should extend the grass program search so that they are included.

[it seems it does this by adding them to `PATH`.](https://github.com/OSGeo/grass/blob/e8c3ff21ddaeb0256dc9bfa291b0136e724b06ed/lib/init/grass.py#L708)

**Comment by zarch** [comment]
@albertoparadisllop you are right, at the moment we add:

```python
    env["GRASS_ADDON_BASE"] = addon_base
    if os.path.join(addon_base, "bin") not in env["PATH"]:
        env["PATH"] += os.pathsep + os.path.join(addon_base, "bin")
    if platform != "win32":
        if os.path.join(addon_base, "scripts") not in env["PATH"]:
            env["PATH"] += os.pathsep + os.path.join(addon_base, "scripts")
```
https://github.com/zarch/grass-session/blob/6097f834be20ee0d703deb2af90f22d6dc66f368/grass_session/session.py#L193

I'm open to a PR to add also the `GRASS_ADDON_PATH`.
