### ISSUE TITLE
Example using GeoTIFF to create location?

### ISSUE THREAD

**Issue by mankoff** [zarch/grass-session#7]
Bash grass supports the `-c file.tif` option to create a location based on a file. I don't see mention of this if I read the docstring for `PERMANENT.open?`

**Comment by zarch** [comment]
[I added a description](https://github.com/zarch/grass-session/commit/59f316ca81be5f35cb690b27bb5bdb70933aff67) to the `open` docstring method.

Basically the `create_opts` parameters in `open` or `create` methods accept any string that is accepted by GRASS GIS `-c` flag. So valid `create_opts` parameters are for instance: `"EPSG:3035"` or `"/tmp/cea.tif"`.

Let me know if you think that the description can be improved, or, if it is easier, just send me a PR. :-D

**Comment by mankoff** [comment]
Neat - functionality was there. Thanks for the added documentation.
